#!/usr/bin/perl -w
use strict;
use YAML;
use DateTime;

my $html_page = "$ENV{HOME}/public_html/mozilla-try.html";
my $builds_dir = "$ENV{HOME}/mozilla-try/builds";

my @builds = map { YAML::LoadFile($_) } glob "$builds_dir/*.build";
@builds = sort { $a->{date} <=> $b->{date} } @builds;

my $content = '';
foreach my $build (@builds) {
    my $dt = DateTime->from_epoch(epoch => $build->{date});
    my $date = $dt->ymd . ' ' . $dt->hms;
    my $git_commit = "<a href=\"https://gitweb.torproject.org/tor-browser.git/commit/$build->{gitcommit}\">$date</a>";
    my $results = "<a href=\"https://treeherder.mozilla.org/#/jobs?repo=try&amp;revision=$build->{hgcommit}\">results</a>";
    my $files = "<a href=\"https://ftp.mozilla.org/pub/mozilla.org/firefox/try-builds/mikeperry\@torproject.org-$build->{hgcommit}/\">files</a>";
    $content .= "$git_commit - $results - $files<br />";
}

open(my $output, '>', $html_page) || die "Error opening $html_page";

my $page = <<END;
<html>
<head>
        <title>Tor Browser - Mozilla Try</title>
<head>
<body>
$content
</body>
</html>
END
print $output $page;
