#!/bin/bash
try_remote_dir=/home/boklm/mozilla-try
try_local_dir=$HOME/mozilla-try
builds_remote_dir=$try_remote_dir/builds
builds_local_dir=$try_local_dir/builds
try_hg_remote_dir=$try_remote_dir/mozilla-esr24
try_hg_local_dir=$try_local_dir/mozilla-esr24

submit_build() {
    local buildid="$1"
    rsync -avH --delete "$try_hg_remote_dir"/ "$try_hg_local_dir"
    echo "Pushing $buildid to Mozilla Try"
    cd "$try_hg_local_dir"
    hg push -f -r "$buildid" ssh://hg.mozilla.org/try > \
        "$builds_local_dir/$buildid.done" 2>&1
}

submit_builds() {
    for build in $builds_remote_dir/*.build
    do
        buildid=$(basename $build | sed 's/\.build$//')
        [ -f "$builds_local_dir/$buildid.done" ] && continue
        submit_build $buildid
    done
}

mkdir -p $(dirname $try_hg_local_dir) $builds_local_dir
while true
do
    submit_builds
    sleep 900
done
