#!/bin/sh
set -e
basedir=$(dirname $0)
. "$basedir/common"

while true
do
    hgrepo=$(inotifywait -e modify --format '%f' "$inotifydir" 2> /dev/null)
    pushd "$MOZILLA_HG_DIR/$hgrepo" > /dev/null
    echo "Pushing $hgrepo"
    $hg push -f ssh://hg.mozilla.org/try
    popd > /dev/null
done
