#!/bin/bash
set -e
try_hg_remote_dir=/home/boklm/mozilla-try/mozilla-esr24
try_hg_local_dir=$HOME/mozilla-try/mozilla-esr24

mkdir -p $(dirname $try_hg_local_dir)
last_submit=0
[ -f "$try_hg_local_dir.changed" ] && last_submit=$(cat "$try_hg_local_dir.changed")
rsync "$try_hg_remote_dir.changed" "$try_hg_local_dir.changed"
[ a"$last_submit" == a$(cat "$try_hg_local_dir.changed") ] && exit 0
rsync -avH --delete "$try_hg_remote_dir"/ "$try_hg_local_dir"
echo "Pushing to Mozilla Try"
cd "$try_hg_local_dir"
hg push -f ssh://hg.mozilla.org/try
