#!/bin/bash
# vim: expandtab sw=4
set -e

basedir=$(dirname $0)
. "$basedir/common"
rebase_onto=
COMMIT=
while [ $# != 0 ]
do
    case "$1" in
        --rebase-onto=*)
            rebase_onto="${1#--rebase-onto=}"
            shift
            ;;
        *)
            [ -n "$COMMIT" ] && echo "Bad arguments" && exit 1
            COMMIT="$1"
            shift
            ;;
    esac
done
[ -z "$COMMIT" ] && echo "Missing argument" && exit 2

# trychooser: http://trychooser.pub.build.mozilla.org/
[ -z "$trychooser" ] &&
    trychooser='try: -b d -e -p linux,linux64,linux64-st-an -u reftest,crashtest,xpcshell,jsreftest,marionette,cppunit,jittests,mochitest-1,mochitest-2,mochitest-3,mochitest-4,mochitest-5,mochitest-bc -t none'

hg_clone() {
    lockfile "$lockdir/$hgrepo"
    local hg_dir="$MOZILLA_HG_DIR/$hgrepo"
    if ! [ -d "$hg_dir" ]
    then
        $hg clone -v "https://hg.mozilla.org/releases/$hgrepo" "$hg_dir"
    fi
    cd "$hg_dir"
}

hg_clean_mq() {
    $hg qpop --all
    for p in $($hg qunapplied)
    do
        $hg qdelete "$p"
    done
}

wget -O"$basedir/gecko-mapfile" https://people.mozilla.org/~pmoore/vcs2vcs/gecko-dev/gecko-mapfile
eval $($basedir/find-hg-parent-commit $COMMIT)
patches_dir=$(mktemp -d)
git_commit_hash=$(git show -s --format=format:%H $COMMIT)
torbrowserpatch="$patches_dir/torbrowser.patch"
echo 'Tor Browser changes' > "$torbrowserpatch"
echo >> "$torbrowserpatch"
git log "$ff_git_commit..$COMMIT" >> "$torbrowserpatch"
git diff "$ff_git_commit..$COMMIT" >> "$torbrowserpatch"
hg_clone
hg_clean_mq
$hg pull
$hg update -C "$ff_hg_commit"
$hg qimport -P "$torbrowserpatch"
$hg qnew -m "$trychooser" trychooser
rm -Rf "$patches_dir"
[ -n "$rebase_onto" ] &&
    $hg rebase -d "$rebase_onto" -r qbase..qtip
buildid=$($hg id -i)
builddate=$(date +%s)
cat > "$MOZILLA_HG_DIR/builds/$buildid.build" <<EOF
date: $builddate
hgcommit: $buildid
gitcommit: $git_commit_hash
gitbranch: $COMMIT
EOF
echo "$builddate" > "$MOZILLA_HG_DIR/$hgrepo.changed"
rm -f "$lockdir/$hgrepo"
echo > "$inotifydir/$hgrepo"
